<?php 
	require_once('components/auth.php');
	require_once('../login.php');
	require_once('../functions.php');
	require_once('components/head.php');
	require_once('components/nav.php');
	require_once('components/view_topics.php');
	require_once('components/message.php');
	require_once('components/footer.php');
 ?>